# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- master.custom

pool:
  vmImage: 'vs2017-win2016'  

variables:
  version: 2.0.4.$(Build.BuildId)

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: 'build\\package.proj'
    msbuildVersion: '15.0'
  env:
    APPVEYOR_REPO_BRANCH: $(Build.SourceBranchName)
    APPVEYOR_REPO_TAG: false
    APPVEYOR_BUILD_NUMBER: $(Build.BuildId)
    APPVEYOR_BUILD_VERSION: $(version)

- task: CmdLine@2
  displayName: 'Build Packages'
  inputs:
    script: 'build-pipelines.cmd'
  env:
    BranchName: $(Build.SourceBranchName)
    Version: $(version)
    BuildNumber: $(Build.BuildId)
    Tag: false
    Suffix: 'lcsc'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts'
    ArtifactName: 'drop'
    publishLocation: 'Container'